---
inputs:
  prompt: [data_shared/AO2D_mc_prompt_train129895.root, data_shared/AO2D_mc_nonprompt_train129893.root]
  nonprompt: [data_shared/AO2D_mc_nonprompt_train129893.root, data_shared/AO2D_mc_prompt_train129895.root]
  data: [data_shared/AO2D_data_train129478.root]

selections: (fPt > 4 and fCpa > 0.90 and fCpaXY > 0.90 and fDecayLength < 2) or (fPt < 4 and fCpa > 0.85 and fCpaXY > 0.85 and fDecayLength < 2)
columns_to_keep: [fM, fPt, fDecayLength, fDecayLengthXY, fImpactParameter0, fImpactParameter1, fImpactParameterProduct, fCpa, fCpaXY]

output:
  directory: data_shared
  suffix:
    prompt: _train129895
    nonprompt: _train129893
    data: _train129478
