---
inputs:
  data: [../trainingD0/tree_d0_data.root]

ptmins: [0., 1., 2., 4., 6., 10.]
ptmaxs: [1., 2., 4., 6., 10., 50.]

models: [
  ModelHandler_D0toKpi_pt0.0_1.0.pickle,
  ModelHandler_D0toKpi_pt1.0_2.0.pickle,
  ModelHandler_D0toKpi_pt2.0_4.0.pickle,
  ModelHandler_D0toKpi_pt4.0_6.0.pickle,
  ModelHandler_D0toKpi_pt6.0_10.0.pickle,
  ModelHandler_D0toKpi_pt10.0_50.0.pickle
]
