---
inputs:
  prompt: [data_shared/AO2D_mc_prompt_train129895.root]
  nonprompt: [data_shared/AO2D_mc_nonprompt_train129893.root]
  data: [data_shared/AO2D_data_train129478.root]

selections: null
columns_to_keep: [fM, fPt, fDecayLength, fDecayLengthXY, fImpactParameter0, fImpactParameter1, fCpa, fCpaXY]

output:
  directory: data_shared
  suffix:
    prompt: _train129895
    nonprompt: _train129893
    data: _train129478.root
