---
inputs:
  #data: data/histograms.root
  data: /Users/lucamicheletti/cernbox/Jpsi_D0_analysis/train_137585/tree_jpsi_d0_reduced_data_merged_BDT_modular_cut.root
  hist: hSparseJPsiDmeson_proj_3_2
  tree: treeJpsiD0

prefilter:
  data: /Users/lucamicheletti/cernbox/Jpsi_D0_analysis/train_137585/tree_jpsi_d0_reduced_data_merged.root
  tree: treeJpsiD0
  cuts: "(fPtD0 >= 0.  && fPtD0 < 1.  && fBdtBkg < 0.050) ||
         (fPtD0 >= 1.  && fPtD0 < 2.  && fBdtBkg < 0.050) ||
         (fPtD0 >= 2.  && fPtD0 < 3.  && fBdtBkg < 0.100) ||
         (fPtD0 >= 3.  && fPtD0 < 4.  && fBdtBkg < 0.100) ||
         (fPtD0 >= 4.  && fPtD0 < 6.  && fBdtBkg < 0.200) ||
         (fPtD0 >= 6.  && fPtD0 < 8.  && fBdtBkg < 0.300) ||
         (fPtD0 >= 8.  && fPtD0 < 10. && fBdtBkg < 0.300) ||
         (fPtD0 >= 10. && fPtD0 < 20. && fBdtBkg < 0.500) ||
         (fPtD0 >= 20. && fPtD0 < 50. && fBdtBkg < 0.500)"
  suffix: _BDT_modular_cut

fit:
  toy_mc: False
  unbinned: True

  cb_par_jpsi_name: [meanJpsi, sigmaJpsi, alphaJpsi, nJpsi]
  cb_par_jpsi_val: [3.0744e+00, 9.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_jpsi_lw_lim: [3.0744e+00, 9.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_jpsi_up_lim: [3.0744e+00, 9.5466e-02, 1.0725e+00, 1.0000e+01]

  cheby_par_jpsi_name: [cheb_coeff_jpsi_0, cheb_coeff_jpsi_1, cheb_coeff_jpsi_2]
  cheby_par_jpsi_val: [-9.8811e-01, 3.0284e-01, -8.3266e-02]
  cheby_par_jpsi_lw_lim: [-9.8811e-01, 3.0284e-01, -8.3266e-02]
  cheby_par_jpsi_up_lim: [-9.8811e-01, 3.0284e-01, -8.3266e-02]

  cb_par_d0_name: [meanD0, sigmaD0, alphaD0, nD0]
  #cb_par_d0_val: [1.8600e+00, 2.2635e-02]
  #cb_par_d0_lw_lim: [1.8600e+00, 2.2635e-02]
  #cb_par_d0_up_lim: [1.8600e+00, 2.2635e-02]
  cb_par_d0_val: [1.8592e+00, 2.1980e-02, 3.2386e+00, 2.3591e-09]
  cb_par_d0_lw_lim: [1.8592e+00, 2.1980e-02, 3.2386e+00, 2.3591e-09]
  cb_par_d0_up_lim: [1.8592e+00, 2.1980e-02, 3.2386e+00, 2.3591e-09]

  cheby_par_d0_name: [cheb_coeff_d0_0, cheb_coeff_d0_1, cheb_coeff_d0_2]
  #cheby_par_d0_val: [-1.7735e-01, -2.5525e-02, 1.6542e-03]
  #cheby_par_d0_lw_lim: [-1.7735e-01, -2.5525e-02, 1.6542e-03]
  #cheby_par_d0_up_lim: [-1.7735e-01, -2.5525e-02, 1.6542e-03]
  cheby_par_d0_val: [-3.8663e-01, 5.8992e-03, 3.4230e-04]
  cheby_par_d0_lw_lim: [-3.8663e-01, 5.8992e-03, 3.4230e-04]
  cheby_par_d0_up_lim: [-3.8663e-01, 5.8992e-03, 3.4230e-04]

output:
  directory: outputs
  figures: figures
